name: Update README with RSS feed

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Fetch RSS feed and generate HTML
        run: python scripts/generate_html.py "$(curl -s "https://www.goldfinch.me/rss")" > styled_rss_content.html
      
      - name: Replace placeholder in README
        run: |
          python scripts/replace_placeholder.py styled_rss_content.html TEMPLATE.md          

      - name: Check if README has changed
        id: check_changes
        run: |
          git diff --exit-code README.md || echo "::set-output name=changed::true"

      - name: Commit changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest styled RSS feed"
          git push "https://${{ secrets.PAT_TOKEN }}@github.com/liamgold/liamgold.git"
